version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: beauty-parlour-db
    restart: always
    environment:
      MYSQL_DATABASE: BeautyParlour
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
