version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: beauty-parlour-db
    restart: always
    environment:
      MYSQL_DATABASE: BeautyParlour
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: beauty-parlour-admin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
